language: perl
perl:
  - "5.24"

os: linux

cache:
  directories:
    - /home/travis/.java/

before_install:
  - JDK_OS="$TRAVIS_OS_NAME"
  - JDK_ARCH="x64"
  - JDK_VERSION="7u80"
  - JDK_BUILD_VERSION="$JDK_VERSION-b15"
  - JDK_FILE="jdk-$JDK_VERSION-$JDK_OS-$JDK_ARCH.tar.gz"
  - JDK_URL="http://people.cs.umass.edu/~rjust/defects4j/download/$JDK_FILE";
  - if [ ! -f "$JDK_FILE" ]; then mkdir -p /home/travis/.java && wget -nv  "$JDK_URL" && tar -xzf "$JDK_FILE" -C /home/travis/.java; fi

install:
# switch to Java-7
  - export JAVA_HOME=/home/travis/.java/jdk1.7.0_80
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
# get apache ant
  - wget --no-check-certificate http://apache.mirrors.lucidnetworks.net//ant/binaries/apache-ant-1.9.13-bin.zip
  - unzip -o -q apache-ant-1.9.13-bin.zip
  - mv apache-ant-1.9.13 apache-ant
# get and prepare D4J
  - git clone https://github.com/jose/defects4j.git defects4j
  - pushd .
  - cd defects4j
  - git checkout fault-localization
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | cpan
  - cpan install Carton
  - carton install
  - ./init.sh
  - popd

before_script:
  - export ANT_HOME=$TRAVIS_BUILD_DIR/apache-ant
  - export D4J_HOME=$TRAVIS_BUILD_DIR/defects4j
  - cd $D4J_HOME

jobs:
  include:
    - stage: Test
# Chart
      script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Chart $(shuf -i 1-26 -n 1)
# Closure
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Closure $(shuf -i 1-133 -n 1)
# Lang
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Lang $(shuf -i 1-65 -n 1)
# Math
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Math $(shuf -i 1-106 -n 1)
# Mockito
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Mockito $(shuf -i 1-38 -n 1)
# Time
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
    - script: travis_wait 40 carton exec $TRAVIS_BUILD_DIR/main.sh Time $(shuf -i 1-27 -n 1)
